;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagRedirects=(OldTagName="Skills.Base.PreviewBuilding",NewTagName="Skills.Base.Building.PreviewBuilding")
GameplayTagRedirects=(OldTagName="Skills.Base.SetBlock",NewTagName="Skills.Base.Building.SetBlock")
GameplayTagRedirects=(OldTagName="Skills.Base.Building.SetBlock",NewTagName="Skills.Base.Building.SetVoxel")
GameplayTagRedirects=(OldTagName="Skills.Base.Building.TraceToBreak",NewTagName="Skills.Base.Building.TraceToBreakBuilding")
GameplayTagRedirects=(OldTagName="Attributes.Base.MovingSpeed",NewTagName="Attributes.Base.Movement.MovingSpeed")
GameplayTagRedirects=(OldTagName="Attributes.Base.JumpStrength",NewTagName="Attributes.Base.Movement.JumpStrength")
GameplayTagList=(Tag="Attributes.Armour.Cutting",DevComment="")
GameplayTagList=(Tag="Attributes.Armour.Electrical",DevComment="")
GameplayTagList=(Tag="Attributes.Armour.FallDamage",DevComment="")
GameplayTagList=(Tag="Attributes.Armour.Fire",DevComment="")
GameplayTagList=(Tag="Attributes.Armour.Frost",DevComment="")
GameplayTagList=(Tag="Attributes.Armour.Physic",DevComment="")
GameplayTagList=(Tag="Attributes.Armour.Piercing",DevComment="")
GameplayTagList=(Tag="Attributes.Armour.Poison",DevComment="")
GameplayTagList=(Tag="Attributes.Armour.Radiation",DevComment="")
GameplayTagList=(Tag="Attributes.Armour.Silver",DevComment="")
GameplayTagList=(Tag="Attributes.Armour.Water",DevComment="")
GameplayTagList=(Tag="Attributes.Attack",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Clear",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Cutting",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Electrical",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.FallDamage",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Fire",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Frost",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Physic",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Piercing",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Poison",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Radiation",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Silver",DevComment="")
GameplayTagList=(Tag="Attributes.Attack.Water",DevComment="")
GameplayTagList=(Tag="Attributes.Base.AnimationsSpeed",DevComment="")
GameplayTagList=(Tag="Attributes.Base.CriticalHitChance",DevComment="")
GameplayTagList=(Tag="Attributes.Base.Health",DevComment="")
GameplayTagList=(Tag="Attributes.Base.Mana",DevComment="")
GameplayTagList=(Tag="Attributes.Base.Movement",DevComment="")
GameplayTagList=(Tag="Attributes.Base.Movement.Friction",DevComment="")
GameplayTagList=(Tag="Attributes.Base.Movement.JumpStrength",DevComment="")
GameplayTagList=(Tag="Attributes.Base.Movement.Loudness",DevComment="")
GameplayTagList=(Tag="Attributes.Base.Movement.MovingSpeed",DevComment="")
GameplayTagList=(Tag="Attributes.Base.Stamina",DevComment="")
GameplayTagList=(Tag="Attributes.Base.Vomit",DevComment="")
GameplayTagList=(Tag="Attributes.Base.Weight",DevComment="")
GameplayTagList=(Tag="Attributes.Magic",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Clear",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Cutting",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Electrical",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Fire",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Frost",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Physic",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Piercing",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Poison",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Radiation",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Silver",DevComment="")
GameplayTagList=(Tag="Attributes.Magic.Water",DevComment="")
GameplayTagList=(Tag="Attributes.Parry",DevComment="")
GameplayTagList=(Tag="Attributes.Parry.Cutting",DevComment="")
GameplayTagList=(Tag="Attributes.Parry.Electrical",DevComment="")
GameplayTagList=(Tag="Attributes.Parry.Fire",DevComment="")
GameplayTagList=(Tag="Attributes.Parry.Frost",DevComment="")
GameplayTagList=(Tag="Attributes.Parry.Physic",DevComment="")
GameplayTagList=(Tag="Attributes.Parry.Piercing",DevComment="")
GameplayTagList=(Tag="Attributes.Parry.Poison",DevComment="")
GameplayTagList=(Tag="Attributes.Parry.Radiation",DevComment="")
GameplayTagList=(Tag="Attributes.Parry.Silver",DevComment="")
GameplayTagList=(Tag="Attributes.Parry.Water",DevComment="")
GameplayTagList=(Tag="Effects",DevComment="")
GameplayTagList=(Tag="Effects.Negative",DevComment="")
GameplayTagList=(Tag="Effects.Negative.Burning",DevComment="")
GameplayTagList=(Tag="Effects.Negative.CantMove",DevComment="")
GameplayTagList=(Tag="Effects.Negative.Concentration",DevComment="")
GameplayTagList=(Tag="Effects.Negative.Electricity",DevComment="")
GameplayTagList=(Tag="Effects.Negative.ElectriclaShock",DevComment="")
GameplayTagList=(Tag="Effects.Negative.Frost",DevComment="")
GameplayTagList=(Tag="Effects.Negative.Hands.BusyHands",DevComment="")
GameplayTagList=(Tag="Effects.Negative.Hands.CantSwitchHandItem",DevComment="")
GameplayTagList=(Tag="Effects.Negative.IceCube",DevComment="")
GameplayTagList=(Tag="Effects.Negative.Knocked",DevComment="")
GameplayTagList=(Tag="Effects.Negative.Poison",DevComment="")
GameplayTagList=(Tag="Effects.Negative.Ragdoll",DevComment="")
GameplayTagList=(Tag="Effects.Negative.V",DevComment="")
GameplayTagList=(Tag="Effects.Neutral",DevComment="")
GameplayTagList=(Tag="Effects.Neutral.CantHaveEffects",DevComment="")
GameplayTagList=(Tag="Effects.Neutral.InWater",DevComment="")
GameplayTagList=(Tag="Effects.Neutral.Oil",DevComment="")
GameplayTagList=(Tag="Effects.Positive",DevComment="")
GameplayTagList=(Tag="Effects.Positive.AddHealth",DevComment="")
GameplayTagList=(Tag="Effects.Positive.HealFrom",DevComment="")
GameplayTagList=(Tag="Effects.Positive.HealFrom.HealFromElectricity",DevComment="")
GameplayTagList=(Tag="Effects.Positive.HealFrom.HealFromFire",DevComment="")
GameplayTagList=(Tag="Effects.Positive.Regeneration",DevComment="")
GameplayTagList=(Tag="Effects.Positive.Strength",DevComment="")
GameplayTagList=(Tag="Skills",DevComment="")
GameplayTagList=(Tag="Skills.Adventure",DevComment="")
GameplayTagList=(Tag="Skills.Base",DevComment="")
GameplayTagList=(Tag="Skills.Base.Building.BreakBuilding",DevComment="")
GameplayTagList=(Tag="Skills.Base.Building.PreviewBuilding",DevComment="")
GameplayTagList=(Tag="Skills.Base.Building.SetVoxel",DevComment="")
GameplayTagList=(Tag="Skills.Base.Building.TraceToBreakBuilding",DevComment="")
GameplayTagList=(Tag="Skills.Base.Fight.Block",DevComment="")
GameplayTagList=(Tag="Skills.Base.Fight.Die",DevComment="")
GameplayTagList=(Tag="Skills.Base.Fight.Heal",DevComment="")
GameplayTagList=(Tag="Skills.Base.Fight.Parry",DevComment="")
GameplayTagList=(Tag="Skills.Base.Fight.Punch",DevComment="")
GameplayTagList=(Tag="Skills.Base.Fight.Reload",DevComment="")
GameplayTagList=(Tag="Skills.Base.Fight.Shoot",DevComment="")
GameplayTagList=(Tag="Skills.Base.Fight.TakeDamage",DevComment="")
GameplayTagList=(Tag="Skills.Base.Movement",DevComment="")
GameplayTagList=(Tag="Skills.Base.Movement.Climb",DevComment="")
GameplayTagList=(Tag="Skills.Base.Movement.Dash",DevComment="")
GameplayTagList=(Tag="Skills.Base.Movement.Jump",DevComment="")
GameplayTagList=(Tag="Skills.Base.Movement.Land",DevComment="")
GameplayTagList=(Tag="Skills.Base.Movement.Move",DevComment="")
GameplayTagList=(Tag="Skills.Base.Movement.MovingInterface",DevComment="")
GameplayTagList=(Tag="Skills.Base.Movement.Run",DevComment="")
GameplayTagList=(Tag="Skills.Base.Movement.Swim",DevComment="")
GameplayTagList=(Tag="Skills.Base.Movement.SwimFast",DevComment="")
GameplayTagList=(Tag="Skills.Base.TakeItem",DevComment="")
GameplayTagList=(Tag="Skills.Base.Throw",DevComment="")
GameplayTagList=(Tag="Skills.Base.TraceToInteract",DevComment="")
GameplayTagList=(Tag="Skills.Magic",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Earth",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Earth.Alpha",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Earth.Beta",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Electricity",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Electricity.Alpha",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Electricity.Beta",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Fire",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Fire.Alpha",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Fire.Alpha.fire_ball",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Fire.Alpha.fire_resist",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Fire.Alpha.fire_row",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Fire.Alpha.fire_throw",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Fire.Beta",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Water",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Water.Alpha",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Water.Beta",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Wind",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Wind.Alpha",DevComment="")
GameplayTagList=(Tag="Skills.Magic.Wind.Beta",DevComment="")
GameplayTagList=(Tag="Skills.Technology",DevComment="")

