;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Skills.gay",NewTagName="Skills.Magic")
+GameplayTagRedirects=(OldTagName="Skills.Magic.Fire.FireBall",NewTagName="Skills.Magic.Fire.fire_ball")
+GameplayTagRedirects=(OldTagName="Skills.Magic.Fire.FireResist",NewTagName="Skills.Magic.Fire.fire_resist")
+GameplayTagRedirects=(OldTagName="Skills.Magic.Fire.FireRow",NewTagName="Skills.Magic.Fire.fire_row")
+GameplayTagRedirects=(OldTagName="Skills.Magic.Fire.FireThrow",NewTagName="Skills.Magic.Fire.fire_throw")
+GameplayTagRedirects=(OldTagName="Skills.Magic.Fire.fire_ball",NewTagName="Skills.Magic.Fire.Alpha.fire_ball")
+GameplayTagRedirects=(OldTagName="Skills.Magic.Fire.fire_resist",NewTagName="Skills.Magic.Fire.Alpha.fire_resist")
+GameplayTagRedirects=(OldTagName="Skills.Magic.Fire.fire_row",NewTagName="Skills.Magic.Fire.Alpha.fire_row")
+GameplayTagRedirects=(OldTagName="Skills.Magic.Fire.fire_throw",NewTagName="Skills.Magic.Fire.Alpha.fire_throw")
+GameplayTagRedirects=(OldTagName="Skills.Base.PunchTwoHands",NewTagName="Skills.Base.PunchTwoHandsLeft")
+GameplayTagRedirects=(OldTagName="Skills.Base.Combo1",NewTagName="Skills.Base.Combo3")
+GameplayTagRedirects=(OldTagName="Skills.Base.Combo2",NewTagName="Skills.Base.Combo")
+GameplayTagRedirects=(OldTagName="Skills.Base.PunchRight",NewTagName="Skills.Base.Punch")
+GameplayTagRedirects=(OldTagName="Skills.Base.Block",NewTagName="Skills.Base.Fight.Block")
+GameplayTagRedirects=(OldTagName="Skills.Base.Punch",NewTagName="Skills.Base.Fight.Punch")
+GameplayTagRedirects=(OldTagName="Skills.Base.TakeDamage",NewTagName="Skills.Base.Fight.TakeDamage")
+GameplayTagRedirects=(OldTagName="Skills.Base.Reload",NewTagName="Skills.Base.Fight.Reload")
+GameplayTagRedirects=(OldTagName="Skills.Base.Die",NewTagName="Skills.Base.Fight.Die")
+GameplayTagRedirects=(OldTagName="Skills.Base.Run",NewTagName="Skills.Base.Movement.Run")
+GameplayTagRedirects=(OldTagName="Skills.Base.Move",NewTagName="Skills.Base.Movement.Move")
+GameplayTagRedirects=(OldTagName="Skills.Base.Jump",NewTagName="Skills.Base.Movement.Jump")
+GameplayTagRedirects=(OldTagName="Skills.Base.Land",NewTagName="Skills.Base.Movement.Land")
+GameplayTagRedirects=(OldTagName="Effects.Negative.BusyHands",NewTagName="Effects.Negative.Hands.BusyHands")
+GameplayTagRedirects=(OldTagName="Skills.Base.Fight",NewTagName="Skills.Fight")

